### PR TITLE
Add back backend changes + update frontend

### PR DESCRIPTION
**Pull request by chanteriam**
## Describe your changes
Adds back the changes from Aicha's Backend Testing PR and Sarah's models PR. Also alters the frontend to collect price from users creating an event and to require an event description.

## Checklist before merging

- [x] My code produces no errors when run
- [x] My code is linted and properly formatted

### CODE REVIEW

**Comment by necabotheking** [comment]
Did you mean to delete manage.py and many of the other backend files?

**Comment by chanteriam** [comment]
> Did you mean to delete manage.py and many of the other backend files?

Yeah, those files existed in the wrong version of the folder (in ShoulderToShoulder/ShoulderToShoulder). If you look at the files in backend/shoulder, they're all still there

**Review by necabotheking — COMMENTED** [review]
Looks Good!

**Review by necabotheking — APPROVED** [review]

**Review by sarahwalker10 — APPROVED** [review]
I see everything there.

**Pull request merged**
