### PR TITLE
Sets up the onboarding page

### PR DESCRIPTION
**Pull request by chanteriam**
## Describe your changes
This PR sets up the onboarding page's dynamic interaction between the backend and the frontend. Through this, users are now able to sign up and be immediately taken to the onboarding page. A user can exit the onboarding process and log in to be taken back to the onboarding page, and their data will be saved.

## Which files am I reviewing
The main files that need review are those in `frontend/s2s/app/src/`. Mostly, these files need to be reviewed for documentation clarity.

## How to run this thing
To work with the onboarding process, you need to serve both the backend and the frontend. 
First, ensure you have the .env file needed to run the backend. The file should be saved to `backend/shoulder/ShoulderToShoulder/.env` and can be found in a pinned message in the backend slack channel.

Open VS code and create two terminals. In the first terminal, serve the backend by running these commands:
```
cd backend/shoulder
poetry shell
poetry install // optional
python manage.py runserver
```
These commands will serve the backend to http://localhost:8000, where the frontend directs the api calls.

In the second terminal, serve the frontend by running these commands:
```
cd frontend/s2d
npm install
ng serve
```
This will serve the frontend to http://localhost:4200.

Next, navigate to http://localhost:4200/#/sign-up to sign up for the application. Create an account using this form and work through the onboarding process.

Note: Running `ng test` will no longer work because of the authentication required for API calls. I am still working on a way to test around this.

To see if your data was updated in the backend, navigate to http://localhost:8000/admin and log in using these credentials:
- username: s2sadmin
- password: s2sadmin123

Once there, click on the "Users" table to see your data!

## Checklist before merging

- [x] My code produces no errors when run
- [x] My code is linted and properly formatted

### CODE REVIEW

**Comment by sarahwalker10** [comment]
I'm missing the backend ".env" file with secret keys. Can you please send it to me or upload it to the drive, and also lmk which directory it should be saved under?

**Comment by sarahwalker10** [comment]
IT WORKS!! :D

**Review by sarahwalker10 — APPROVED** [review]
Able to go through on boarding process and can see my information is being saved to the db in the backend

**Comment by chanteriam** [comment]
> Able to go through on boarding process and can see my information is being saved to the db in the backend

YAYAYAYAYAYAY!!!!!!!!

**Comment by necabotheking** [comment]
Looks wonderful! Thanks so much for the small changes and clear documentation!

**Pull request merged**
