### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by chanteriam**
## Describe your changes
This PR sets up the user profile page. This includes the profile overview page, the user availability page, and the settings page. 

- one **can** successfully update their availability, onboarding questionnaire, password, user data, and they can delete their account
- one **can not** yet see an accurate list of the events you have attended and events that are upcoming.

## Files to review
This PR includes edits to both the front and the backend. The primary files that need review are:
- backend: `backend/shoulder/s2s/views.py`, specifically the ProfileViewSet and the UserViewSet
- frontend: 'frontend/s2s/src/app/`, specifically:
    - `_services/auth.service.ts`
    - `_services/profile.service.ts`
    - `_services/event.service.ts`
    - `available-display/availability-display.component.ts`
    - `profile/profile.component.ts`
    - `profile-availability/profile-availability.component.ts`
    - `profile-overview/profile-overview.component.ts`
    - `profile-settings/profile-settings.component.ts`

## How to run this thing
You should have previously created an S2S account when testing onboarding. Through these steps, you can log into your account using your previous credentials, or you can sign up for an account.

You need to serve both the backend and the frontend. 
First, ensure you have the .env file needed to run the backend. The file should be saved to `backend/shoulder/ShoulderToShoulder/.env` and can be found in a pinned message in the backend slack channel.

Open VS code and create two terminals. In the first terminal, serve the backend by running these commands:
```
cd backend/shoulder
poetry shell
poetry install // optional
python manage.py runserver
```
These commands will serve the backend to http://localhost:8000, where the frontend directs the api calls.

In the second terminal, serve the frontend by running these commands:
```
cd frontend/s2d
npm install
ng serve
```
This will serve the frontend to http://localhost:4200.

Next, navigate to http://localhost:4200/#/log-in to log into your existing account. You will be automatically taken to your profile page.

Alternatively, if you don't have an account, navigate to http://localhost:4200/#/sign-up to sign up for the application. Create an account using this form and work through the onboarding process. After the process is complete, you will be redirected to your profile.

Note: Running `ng test` will no longer work because of the authentication required for API calls. I am still working on a way to test around this.

To see if your data was updated in the backend, navigate to http://localhost:8000/admin and log in using these credentials:
- username: s2sadmin
- password: s2sadmin123

## Checklist before merging
- [x] My code produces no errors when run
- [x] My code is linted and properly formatted

### CODE REVIEW

**Review by sarahwalker10 — CHANGES_REQUESTED** [review]
1. Error on the frontend when I try to run `ng serve`:
```
⠏ Building...
✘ [ERROR] TS2307: Cannot find module '@ngneat/cashew' or its corresponding type declarations. [plugin angular-compiler]

    src/app/_interceptors/cache.ts:4:26:
      4 │ import { withCache } from '@ngneat/cashew';
        ╵                           ~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module '@ngneat/cashew' or its corresponding type declarations. [plugin angular-compiler]

    src/app/_services/calendar.service.ts:5:26:
      5 │ import { withCache } from '@ngneat/cashew';
        ╵                           ~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'moment' or its corresponding type declarations. [plugin angular-compiler]

    src/app/_services/event.service.ts:4:19:
      4 │ import moment from 'moment';
        ╵                    ~~~~~~~~


✘ [ERROR] TS2307: Cannot find module '@ngneat/cashew' or its corresponding type declarations. [plugin angular-compiler]

    src/app/app.module.ts:11:59:
      11 │ ...rovideHttpCache, withHttpCacheInterceptor } from '@ngneat/cashew';
         ╵                                                     ~~~~~~~~~~~~~~~~

Application bundle generation failed. [5.681 seconds]
```

2. One more thing - this wasn't a part of your changes, but a small typo I noticed. Thought it might be easier for you to fix the file and make the migrations since this branch has the most up to date changes:

`backend/shoulder/s2s/db_models/event.py` , lines 28 and 29 should be opposites:
```
MinValueValidator(2),
MaxValueValidator(50)])
```

**Comment by sarahwalker10** [comment]
Note to other team members that 2 variables need to be added to `backend/shoulder/ShoulderToShoulder/.env` in order to run this thing: 

AWS_STORAGE_BUCKET_NAME=s2s-profile-photos
AWS_S3_REGION_NAME=us-east-2

**Comment by chanteriam** [comment]
> 1. Error on the frontend when I try to run `ng serve`:
> 
> ```
> ⠏ Building...
> ✘ [ERROR] TS2307: Cannot find module '@ngneat/cashew' or its corresponding type declarations. [plugin angular-compiler]
> 
>     src/app/_interceptors/cache.ts:4:26:
>       4 │ import { withCache } from '@ngneat/cashew';
>         ╵                           ~~~~~~~~~~~~~~~~
> 
> 
> ✘ [ERROR] TS2307: Cannot find module '@ngneat/cashew' or its corresponding type declarations. [plugin angular-compiler]
> 
>     src/app/_services/calendar.service.ts:5:26:
>       5 │ import { withCache } from '@ngneat/cashew';
>         ╵                           ~~~~~~~~~~~~~~~~
> 
> 
> ✘ [ERROR] TS2307: Cannot find module 'moment' or its corresponding type declarations. [plugin angular-compiler]
> 
>     src/app/_services/event.service.ts:4:19:
>       4 │ import moment from 'moment';
>         ╵                    ~~~~~~~~
> 
> 
> ✘ [ERROR] TS2307: Cannot find module '@ngneat/cashew' or its corresponding type declarations. [plugin angular-compiler]
> 
>     src/app/app.module.ts:11:59:
>       11 │ ...rovideHttpCache, withHttpCacheInterceptor } from '@ngneat/cashew';
>          ╵                                                     ~~~~~~~~~~~~~~~~
> 
> Application bundle generation failed. [5.681 seconds]
> ```
> 
>  2. One more thing - this wasn't a part of your changes, but a small typo I noticed. Thought it might be easier for you to fix the file and make the migrations since your branch has the most up to date changes:
> 
> `backend/shoulder/s2s/db_models/event.py` , lines 28 and 29 should be opposites:
> 
> ```
> MinValueValidator(2),
> MaxValueValidator(50)])
> ```

Hi Sarah, for the first error, you need to run npm install to get those missing packages :)

**Review by sarahwalker10 — APPROVED** [review]
Note that the availability updating is slow to update in the database - would require users to remain on the page for at least 2 minutes after they update their availability to be sure that their changes get saved. 

Also the text on the profile page buttons does not adjust to smaller screen size, but just a small observation.

**Pull request merged**
