### PR TITLE
Implemented DeepFM model

### PR DESCRIPTION
**Pull request by dscolby**
## Checklist before merging

- [x] My code produces no errors when run
- [x] My code is linted and properly formatted

### CODE REVIEW

**Comment by dscolby** [comment]
Addresses #33.

**Comment by dscolby** [comment]
Also closes #52

**Comment by dscolby** [comment]
Also implemented a dataset class that closes #54

**Review by sarahwalker10 — COMMENTED** [review]
Thank you for this work, Darren! I entered the environment using "poetry shell", and I used "poetry show" to confirm that the pytest package is installed, but for some reason I keep getting the error "pytest: commend not found" whenever I try to run the testing scripts. These are the commands I've tried (inside the poetry environment): 
"poetry run pytest tests/test_file.py", 
"poetry pytest tests/test_file.py", 
"run pytest tests/test_file.py", and 
"pytest tests/test_file.py",

Ans all of them produce the error. Any suggestions?

**Review by sarahwalker10 — CHANGES_REQUESTED** [review]
Can you please add some info to the README? Probably a brief overview of what the model is doing, how to run the files (if applicable), and/or a description of each file and what it is doing.

**Comment by dscolby** [comment]
@sarahwalker10 are you running it from the ml folder as the working directory? I haven't had any issues when calling poetry shell and hen poetry run pytest from within the ml folder. Also, I'm going to use Conda as the package manager whenever we get the repo set up so that we only have one Conda environment, which is why I have a separate issue for porting it to Conda.

**Comment by dscolby** [comment]
Okay @sarahwalker10 I just added a paragraph about DeepFMs to the readme.

**Comment by sarahwalker10** [comment]
Thank you so much, Darren! The README looks great, I appreciate that. And makes much more sense now.

**Comment by sarahwalker10** [comment]
Also! Once I get the pytest running, I'll approve the changes! I would love to see your work updated on the main branch.

**Review by sarahwalker10 — APPROVED** [review]
BTW I resolved the merge conflicts with your README.md and the main branch.

**Review by chanteriam — APPROVED** [review]

**Pull request merged**
